services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.1
    environment:
      - CLICKHOUSE_DB=analytics
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=analytics
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "8123:8123"   # HTTP API
      - "9000:9000"   # Native Protocol
      - "9009:9009"   # Interserver HTTP
    ulimits:
      nofile:
        soft: 262144
        hard: 262144